import os
from fpdf import FPDF
from io import BytesIO

from RenukaSoft import settings

def __gen_pdf__(data):
    # try:
        ID = str(data.get("ID"))
        clienid = str(data.get("clienid"))
        companyname = str(data.get("companyname"))
        DOCID = str(data.get("DOCID"))
        INVDate = str(data.get("INVDate"))
        PONO = str(data.get("PONO"))
        PODate = str(data.get("PODate"))
        ExecId = str(data.get("ExecId"))
        Shipvia = str(data.get("Shipvia"))
        Taxid = str(data.get("Taxid"))
        Terms = str(data.get("Terms"))
        BasicAmount = str(data.get("BasicAmount"))
        Freight = str(data.get("Freight"))
        Insurance = str(data.get("Insurance"))
        TotalAmt = str(data.get("TotalAmt"))
        itemid = str(data.get("itemid"))
        itemname = str(data.get("itemname"))
        classid = str(data.get("classid"))
        classname = str(data.get("classname"))
        quantity = str(data.get("quantity"))
        rate = str(data.get("rate"))
        unitid = str(data.get("unitid"))
        unitname = str(data.get("unitname"))
        amount = str(data.get("amount"))
        addressid = str(data.get("addressid"))
        address = str(data.get("address"))
        country = str(data.get("country"))

        pdf = FPDF('P', 'mm', 'Letter')
        pdf.set_auto_page_break(auto=True, margin=10)
        pdf.add_page()
        # pdf.image("D:\\UpWork\\RenukaSoftec\\SmartMIS-Backend\\media\\proformainvoice\\ssimage.jpg", 10, 8, 15)
        image_path = os.path.join(settings.MEDIA_ROOT, 'proformainvoice/ssimage.jpg')
        image_path = os.path.join(settings.MEDIA_ROOT, 'proformainvoice/ssimage.jpg')
        pdf.image(image_path, 10, 8, 15)
        pdf.set_font('helvetica', 'B', 20)
        pdf.cell(80)
        pdf.set_fill_color(230, 230, 0)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(50, 10, 'SS GROUP INDIA', border=False, ln=1, align='C')

        pdf.ln(5)
        pdf.set_font('times', 'B', 16)
        pdf.cell(200, 8, 'Proforma Invoice', ln=True, border=True, align='C')
        pdf.set_font('times', 'B', 8)
        pdf.set_text_color(0, 0, 0)        
        pdf.set_fill_color(255, 255, 255)  

        pdf.ln()
        pdf.ln()
        pdf.set_xy(10, 40)
        pdf.cell(30, 5, 'Invoice To :', align='L')
        pdf.cell(140, 5, '', align='L')
        pdf.ln()
        pdf.cell(30, 5, 'Company Name :', align='L')
        pdf.cell(140, 5, companyname, align='L')
        pdf.ln()
        pdf.cell(30, 5, 'Address :', align='L')
        pdf.cell(140, 5, address, align='L')
        pdf.ln()
        pdf.cell(30, 5, 'Country :', align='L')
        pdf.cell(140, 5, country, align='L')
        pdf.rect(10, 40, 97, 35)
        pdf.ln(25)
        pdf.cell(32, 5, 'Invoice #', align='L', border=True, fill=True)
        pdf.cell(168, 5, DOCID, align='L', border=True, fill=True)
        pdf.ln()
        pdf.cell(32, 5, 'Invoice Date', align='L', border=True, fill=True)
        pdf.cell(168, 5, INVDate, align='L', border=True, fill=True)
        pdf.ln(15)
        pdf.set_xy(108, 40)
        pdf.cell(20, 5, 'S S Group India', align='L')
        pdf.ln()
        pdf.cell(98, 5, '', align='L')
        pdf.cell(20, 5, 'W-210, MIDC Area', align='L')
        pdf.ln()
        pdf.cell(98, 5, '', align='L')
        pdf.cell(20, 5, 'Behind Reliance Sillicon', align='L')
        pdf.ln()
        pdf.cell(98, 5, '', align='L')
        pdf.cell(20, 5, 'Koparkhairna', align='L')
        pdf.ln()
        pdf.cell(98, 5, '', align='L')
        pdf.cell(20, 5, 'Navi Mumbai, India', align='L')
        pdf.ln()
        pdf.cell(98, 5, '', align='L')
        pdf.cell(102, 5, 'Email : ssgroupi@gmail.com', align='L', border=True, fill=True)
        pdf.ln()
        pdf.cell(98, 5, '', align='L')
        pdf.cell(102, 5, 'Ph : +91 9820180800', align='L', border=True, fill=True)
        pdf.rect(108, 40, 102, 30)
        pdf.ln(25)
        pdf.cell(32, 5, 'Date', align='C', border=True, fill=True)
        pdf.cell(22, 5, 'Your Order #', align='C', border=True, fill=True)
        pdf.cell(22, 5, 'Our Ref. #', align='C', border=True, fill=True)
        pdf.cell(22, 5, 'Our Contact', align='C', border=True, fill=True)
        pdf.cell(22, 5, 'FOB', align='C', border=True, fill=True)
        pdf.cell(26, 5, 'Ship Via', align='C', border=True, fill=True)
        pdf.cell(28, 5, 'Terms', align='C', border=True, fill=True)
        pdf.cell(26, 5, 'Tax ID', align='C', border=True, fill=True)
        pdf.ln()
        pdf.cell(32, 5, PODate, align='C', border=True, fill=True)
        pdf.cell(22, 5, PONO, align='C', border=True, fill=True)
        pdf.cell(22, 5, '', align='C', border=True, fill=True)
        pdf.cell(22, 5, '', align='C', border=True, fill=True)
        pdf.cell(22, 5, '', align='C', border=True, fill=True)
        pdf.cell(26, 5, Shipvia, align='C', border=True, fill=True)
        pdf.cell(28, 5, Terms, align='C', border=True, fill=True)
        pdf.cell(26, 5, Taxid, align='C', border=True, fill=True)
        pdf.ln(11)
        pdf.cell(10, 5, 'Sr. no.', align='C', border=True, fill=True)
        pdf.cell(66, 5, 'Description', align='C', border=True, fill=True)
        pdf.cell(44, 5, 'Specification', align='C', border=True, fill=True)
        pdf.cell(26, 5, 'Qunatity in Nos.', align='C', border=True, fill=True)
        pdf.cell(28, 5, 'Rate / 1000 FOB USD', align='C', border=True, fill=True)
        pdf.cell(26, 5, 'Total FOB IN USD', align='C', border=True, fill=True)

        for i in range(1, 5):
            pdf.ln()
            pdf.cell(10, i, border=True)
            pdf.cell(66, 5, itemname, border=True)
            pdf.cell(44, 5, classname, border=True)
            pdf.cell(26, 5, quantity, border=True)
            pdf.cell(28, 5, rate, border=True)
            pdf.cell(26, 5, BasicAmount, border=True)

        pdf.ln()
        pdf.cell(193, 5, '')
        pdf.ln()
        pdf.cell(10, 5, '', align='R', border=True, fill=True)
        pdf.cell(164, 5, 'Total FOB value in US$', align='R', border=True, fill=True)
        pdf.cell(26, 5, amount, align='R', border=True, fill=True)
        pdf.ln()
        pdf.cell(10, 5, '', align='R', border=True, fill=True)
        pdf.cell(164, 5, 'Insurance', align='R', border=True, fill=True)
        pdf.cell(26, 5, Insurance, align='R', border=True, fill=True)
        pdf.ln()
        pdf.cell(10, 5, '', align='R', border=True, fill=True)
        pdf.cell(164, 5, 'SEA Freight Charges per container in US$', align='R', border=True, fill=True)
        pdf.cell(26, 5, Freight, align='R', border=True, fill=True)
        pdf.ln()
        pdf.cell(10, 5, '', align='R', border=True, fill=True)
        pdf.cell(164, 5, 'Total CIF amount in US$', align='R', border=True, fill=True)
        pdf.cell(26, 5, TotalAmt, align='R', border=True, fill=True)
        pdf.ln()
        pdf.cell(200, 5, '', align='L', border=True, fill=True)
        pdf.ln()
        pdf.cell(30, 5, 'Paymesdfsdfnt Term :', align='L', border=True, fill=True)
        pdf.cell(170, 5, 'sdlkfjlsdf', align='L', border=True, fill=True)
        pdf.ln(20)
        pdf.cell(200, 5, 'Our Bank Details', align='L', border=False, fill=True)
        pdf.ln(20)
        pdf.cell(200, 5, 'For S.S. Group ( India )', align='L', border=False, fill=True)
        pdf.ln(20)
        pdf.cell(200, 5, 'Authorised Signatory', align='L', border=False, fill=True)
        pdf.ln(20)
        pdf.cell(200, 5, 'W-120, M.I.D.C. IndI. , Area, Koparkhairna, Navi-Mumbai - 400 710, INDIA.', align='C', border=False, fill=True)
        pdf.ln()
        pdf.cell(200, 5, 'Phone: + 91 22(O)2778 7700     Fax:  + 91 22(O)2778 1177 Email: rss@ssgroupindia.com', align='C', border=False, fill=True)
        pdf.rect(10, 171, 200, 90)

        # pdf_buffer = BytesIO()
        # pdf.output("pdf_buffer.pdf")
        # pdf_buffer.seek(0)
        pdf_buffer = BytesIO()
        pdf_data = pdf.output(dest='S').encode('latin1')
        pdf_buffer.write(pdf_data)
        pdf_buffer.seek(0)
        return pdf_buffer
    # except Exception as e :
    #     print(e)
# data = {'ID': 1, 'clienid': '00102', 'companyname': 'ADHUNIK ELECTRODES', 'DOCID': 'SSGI/PFI/23-24/0001', 'INVDate': "datetime.datetime(2024, 7, 26, 0, 0)", 'PONO': '4568952', 'PODate': "datetime.datetime(2024, 7, 25, 0, 0)", 'ExecId': '00006', 'Shipvia': 'SEA', 'Taxid': 0, 'Terms': 'CAD', 'BasicAmount': 100000.0, 'Freight': 25000.0, 'Insurance': 15000.0, 'TotalAmt': 140000.0, 'itemid': '52416', 'itemname': 'STAR GOLD XL OUTER_ELECTRODES\r\n', 'classid': '00166', 'classname': 'Fluted Cartons', 'quantity': 10000, 'rate': 2.5, 'unitid': '00011', 'unitname': 'NOS', 'amount': 25000.0, 'addressid': '00660', 'address': 'RHINO INDUSTRIAL PARK GOURIPUR, AMINGAON, NORTH GUWAHATI GUWAHATI Assam', 'country': 'INDIA'}
# res = __gen_pdf__(data)