# Generated by Django 3.2.19 on 2024-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstItemtypedetail',
            fields=[
                ('int_id', models.AutoField(db_column='Int_ID', primary_key=True, serialize=False)),
                ('label_name', models.CharField(db_column='Label_Name', max_length=50)),
                ('default_value', models.FloatField(db_column='Default_Value')),
                ('min_value', models.FloatField(blank=True, db_column='Min_Value', null=True)),
                ('max_value', models.FloatField(blank=True, db_column='Max_Value', null=True)),
                ('tooltip', models.CharField(db_column='ToolTip', max_length=100)),
                ('seqid', models.IntegerField(blank=True, db_column='SeqID', null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=100, null=True)),
                ('isactive', models.IntegerField(db_column='IsActive')),
                ('isrequired', models.IntegerField(db_column='IsRequired')),
                ('cellheight', models.FloatField(blank=True, db_column='CellHeight', null=True)),
                ('cellwidth', models.FloatField(blank=True, db_column='CellWidth', null=True)),
                ('imgpath', models.CharField(blank=True, db_column='ImgPath', max_length=200, null=True)),
            ],
            options={
                'db_table': 'est_itemtypedetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstItemtypemaster',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('CartonType', models.CharField(db_column='CartonType', max_length=60)),
                ('internalCartonType', models.CharField(db_column='internalCartonType', max_length=60, unique=True)),
                ('imgpath', models.CharField(blank=True, db_column='ImgPath', max_length=200, null=True)),
                ('ecma_code', models.CharField(blank=True, db_column='ECMA_Code', max_length=50, null=True)),
            ],
            options={
                'db_table': 'est_itemtypemaster',
                'managed': False,
            },
        ),
    ]
