# Generated by Django 3.2.19 on 2024-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstProcessInputDetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('prid', models.CharField(db_column='PrID', max_length=50)),
                ('sp_process_no', models.IntegerField(db_column='SP_Process_no')),
                ('input_label_name', models.CharField(max_length=30)),
                ('input_type', models.CharField(blank=True, max_length=30, null=True)),
                ('input_data_type', models.CharField(blank=True, max_length=30, null=True)),
                ('input_default_value', models.CharField(blank=True, max_length=10, null=True)),
                ('Unique_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('seqno', models.IntegerField(blank=True, db_column='SeqNo', null=True)),
                ('isactive', models.IntegerField(blank=True, db_column='IsActive', null=True)),
            ],
            options={
                'db_table': 'est_process_input_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Papermasterfull',
            fields=[
                ('paperid', models.CharField(db_column='PaperId', max_length=10, primary_key=True, serialize=False)),
                ('paperkind', models.CharField(blank=True, db_column='PaperKind', max_length=50, null=True)),
                ('manucompany', models.CharField(blank=True, db_column='ManuCompany', max_length=50, null=True)),
                ('gsm', models.IntegerField(blank=True, db_column='Gsm', null=True)),
                ('grain', models.CharField(blank=True, db_column='Grain', max_length=10, null=True)),
                ('costprice', models.FloatField(blank=True, db_column='CostPrice', null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=10, null=True)),
                ('standardlength', models.FloatField(blank=True, db_column='StandardLength', null=True)),
                ('standardbreadth', models.FloatField(blank=True, db_column='StandardBreadth', null=True)),
                ('pquantity', models.FloatField(blank=True, db_column='PQuantity', null=True)),
                ('stock', models.CharField(db_column='Stock', max_length=20)),
                ('icompanyid', models.CharField(blank=True, db_column='ICompanyID', max_length=10, null=True)),
                ('shperpacket', models.SmallIntegerField(blank=True, db_column='ShPerPacket', null=True)),
                ('packetweight', models.FloatField(blank=True, db_column='PacketWeight', null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=50, null=True)),
                ('isspecial', models.PositiveIntegerField(db_column='IsSpecial')),
                ('pkind', models.CharField(db_column='PKind', max_length=45)),
                ('fsctype', models.IntegerField(db_column='FSCType')),
                ('isactive', models.IntegerField(db_column='IsActive')),
                ('paperbrand', models.CharField(db_column='PaperBrand', max_length=30)),
                ('classid', models.CharField(db_column='Classid', max_length=10)),
                ('bf', models.IntegerField(db_column='BF')),
                ('thickness', models.FloatField(db_column='Thickness')),
                ('uom', models.CharField(db_column='UOM', max_length=10)),
                ('subgroupid', models.IntegerField(db_column='SubGroupID')),
            ],
            options={
                'db_table': 'papermasterfull',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrontendResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_response', models.JSONField()),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
