# Generated by Django 3.2.19 on 2024-03-19 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.CharField(db_column='UserID', max_length=10, primary_key=True, serialize=False)),
                ('userdepartmentid', models.CharField(blank=True, db_column='UserDepartmentID', max_length=10, null=True)),
                ('employeecode', models.CharField(blank=True, db_column='EmployeeCode', max_length=10, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=100, null=True)),
                ('userloginname', models.CharField(blank=True, db_column='UserLoginName', max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='UserPassword', max_length=100, null=True)),
                ('post', models.CharField(blank=True, db_column='Post', max_length=100, null=True)),
                ('joining_date', models.CharField(blank=True, db_column='Joining_Date', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=100, null=True)),
                ('dateofbirth', models.CharField(blank=True, db_column='DateofBirth', max_length=20, null=True)),
                ('ph1', models.CharField(blank=True, db_column='Ph1', max_length=20, null=True)),
                ('ph2', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=20, null=True)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('referreddby', models.CharField(blank=True, db_column='ReferreddBy', max_length=100, null=True)),
                ('isactive', models.IntegerField(blank=True, db_column='IsActive', null=True)),
                ('auid', models.CharField(blank=True, db_column='AUID', max_length=50, null=True)),
                ('adatetime', models.DateTimeField(db_column='ADateTime', default=django.utils.timezone.now)),
                ('muid', models.CharField(blank=True, db_column='MUID', max_length=50, null=True)),
                ('mdatetime', models.CharField(db_column='MDateTime', max_length=50)),
                ('companyid', models.IntegerField(blank=True, db_column='CompanyID', null=True)),
                ('mgtlevels', models.IntegerField(blank=True, db_column='MgtLevels', null=True)),
                ('icompanyid', models.CharField(db_column='Icompanyid', max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usermaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('visibility_condition', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
                ('resend_attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
