# Generated by Django 3.2.19 on 2024-03-19 06:50

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodule',
            options={'ordering': ['-sort']},
        ),
        migrations.RenameField(
            model_name='appmodule',
            old_name='ordering',
            new_name='sort',
        ),
        migrations.RemoveField(
            model_name='appmodule',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='appmodule',
            name='visibility_condition',
        ),
        migrations.AddField(
            model_name='appmodule',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='module_icons/'),
        ),
        migrations.AlterField(
            model_name='appmodule',
            name='url',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
