# Generated by Django 3.2.19 on 2024-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240316_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('visibility_condition', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
