# Generated by Django 3.2.19 on 2024-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingMaster',
            fields=[
                ('coatingid', models.CharField(db_column='CoatingID', max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
                ('isactive', models.PositiveIntegerField(blank=True, db_column='IsActive', null=True)),
                ('cgsm', models.FloatField(db_column='CGSM')),
                ('fullcoatingunit', models.CharField(db_column='FullCoatingUnit', max_length=45)),
                ('fullrate', models.FloatField(db_column='FullRate')),
                ('fullratemin', models.FloatField(db_column='FullRateMin')),
                ('fullmincharges', models.FloatField(db_column='FullMinCharges')),
                ('spotcoatingunit', models.CharField(db_column='SpotCoatingUnit', max_length=45)),
                ('spotrate', models.FloatField(db_column='SpotRate')),
                ('spotratemin', models.FloatField(db_column='SpotRateMin')),
                ('spotratetsh', models.FloatField(db_column='SpotRateTSh')),
                ('spotratetshmin', models.FloatField(db_column='SpotRateTShMin')),
                ('spotmincharges', models.FloatField(db_column='SpotMinCharges')),
                ('minratepersh', models.FloatField(db_column='MinRatePerSh')),
                ('roundoffshby', models.FloatField(db_column='RoundOffShBy')),
                ('mreadywastsh', models.FloatField(db_column='MReadyWastSh')),
                ('runwastper', models.FloatField(db_column='RunWastPer')),
                ('catid', models.CharField(db_column='CatID', max_length=10)),
                ('machineid', models.CharField(db_column='MachineId', max_length=10)),
                ('is_uv_coating', models.IntegerField(blank=True, db_column='Is_uv_coating', null=True)),
                ('extra_plates', models.IntegerField(blank=True, db_column='Extra_Plates', null=True)),
            ],
            options={
                'db_table': 'Coating_Master',
                'managed': False,
            },
        ),
    ]
