# Generated by Django 3.2.19 on 2024-07-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastersapp', '0002_coatingmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoatingMaster',
        ),
        migrations.DeleteModel(
            name='EstJobcomplexity',
        ),
    ]
