# Generated by Django 3.2.19 on 2024-08-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productspecification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMachinenames',
            fields=[
                ('machineid', models.CharField(db_column='MachineID', max_length=10)),
                ('machinename', models.CharField(db_column='MachineName', max_length=45)),
                ('prid', models.CharField(db_column='PrID', max_length=10)),
                ('processname', models.CharField(db_column='ProcessName', max_length=200)),
                ('basepruniqueid', models.IntegerField(db_column='BasePrUniqueID')),
                ('perhrruncost', models.FloatField(db_column='PerHrRunCost')),
                ('powercharges', models.FloatField(db_column='Powercharges')),
                ('labourcharges', models.FloatField()),
                ('interestamt', models.FloatField(db_column='interestAmt')),
                ('depriamt', models.FloatField()),
                ('avgspeed', models.FloatField()),
                ('avgsetuptime', models.FloatField()),
                ('avgwastage', models.FloatField()),
                ('rentpm', models.FloatField()),
                ('maintainpm', models.FloatField()),
                ('consumblepm', models.FloatField()),
                ('capacityperday', models.FloatField(blank=True, db_column='CapacityPerDay', null=True)),
                ('inuse', models.IntegerField(blank=True, db_column='InUse', null=True)),
                ('recid', models.AutoField(db_column='Recid', primary_key=True, serialize=False)),
                ('machineno_internal', models.CharField(blank=True, db_column='MachineNo_Internal', max_length=20, null=True)),
                ('makereadycostnr', models.IntegerField(blank=True, db_column='MakeReadyCostNr', null=True)),
                ('productioncostnr', models.IntegerField(blank=True, db_column='ProductionCostNr', null=True)),
                ('makereadycostuv', models.IntegerField(blank=True, db_column='MakeReadyCostUV', null=True)),
                ('productioncostuv', models.IntegerField(blank=True, db_column='ProductionCostUV', null=True)),
                ('directmanpowcost', models.IntegerField(blank=True, db_column='DirectManpowCost', null=True)),
                ('supportmanpowcost', models.IntegerField(blank=True, db_column='SupportManpowCost', null=True)),
                ('admindepmanpowcost', models.IntegerField(blank=True, db_column='AdminDepManpowCost', null=True)),
                ('pile_height', models.SmallIntegerField()),
                ('pile_weight_limit', models.SmallIntegerField()),
                ('pile_load_time', models.IntegerField()),
                ('speedunit', models.CharField(blank=True, db_column='SpeedUnit', max_length=10, null=True)),
                ('icompanyid', models.CharField(max_length=10)),
                ('arrangeseqno', models.IntegerField()),
            ],
            options={
                'db_table': 'item_machinenames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemProcessname',
            fields=[
                ('prid', models.CharField(db_column='PrID', max_length=50, unique=True)),
                ('prname', models.CharField(db_column='PrName', max_length=45)),
                ('description', models.CharField(db_column='Description', max_length=45)),
                ('unitid', models.CharField(db_column='UnitID', max_length=20)),
                ('isactive', models.PositiveIntegerField(db_column='IsActive')),
                ('level', models.FloatField(db_column='Level')),
                ('narration', models.CharField(max_length=200)),
                ('inputuom', models.CharField(db_column='InputUOM', max_length=10)),
                ('outputuom', models.CharField(db_column='OutPutUOM', max_length=10)),
                ('prodvalidation', models.PositiveIntegerField(db_column='ProdValidation')),
                ('displayinlistbox', models.FloatField(db_column='DisplayInListBox')),
                ('basepruniqueid', models.IntegerField(db_column='BasePrUniqueID')),
                ('basetablename', models.CharField(db_column='BaseTableName', max_length=200)),
                ('canbeonline', models.FloatField(db_column='CanBeOnLine')),
                ('formno', models.CharField(db_column='FormNo', max_length=100)),
                ('donebycontractor', models.IntegerField(db_column='DonebyContractor')),
                ('mrwastage', models.FloatField(db_column='MrWastage')),
                ('processwastage', models.FloatField(db_column='ProcessWastage')),
                ('wastagein', models.CharField(db_column='WastageIn', max_length=10)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tseqno', models.IntegerField(db_column='Tseqno')),
            ],
            options={
                'db_table': 'item_processname',
                'managed': False,
            },
        ),
    ]
