# Generated by Django 3.2.19 on 2024-08-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productspecification', '0002_itemmachinenames_itemprocessname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDropdown',
            fields=[
                ('autoid', models.AutoField(db_column='AutoId', primary_key=True, serialize=False)),
                ('dropdownname', models.CharField(db_column='DropDownName', max_length=50)),
                ('option', models.CharField(db_column='Option', max_length=50)),
                ('value', models.CharField(db_column='Value', max_length=50)),
                ('isactive', models.IntegerField(db_column='IsActive')),
            ],
            options={
                'db_table': 'general_dropdown',
                'managed': False,
            },
        ),
    ]
