# Generated by Django 3.2.19 on 2024-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productspecification', '0003_generaldropdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lammetpetmaster',
            fields=[
                ('lamid', models.CharField(db_column='LamID', max_length=10, primary_key=True, serialize=False)),
                ('filmtype', models.CharField(blank=True, db_column='FilmType', max_length=50, null=True)),
                ('micron', models.SmallIntegerField(blank=True, db_column='Micron', null=True)),
                ('gravity', models.FloatField(blank=True, db_column='Gravity', null=True)),
                ('remarks', models.CharField(db_column='Remarks', max_length=300)),
            ],
            options={
                'db_table': 'lammetpetmaster',
                'managed': False,
            },
        ),
    ]
