# Generated by Django 3.2.19 on 2024-08-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productspecification', '0004_lammetpetmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastingmaster',
            fields=[
                ('pastingid', models.CharField(db_column='PastingID', max_length=10, primary_key=True, serialize=False)),
                ('narration', models.CharField(blank=True, db_column='Narration', max_length=40, null=True)),
                ('inuse', models.PositiveIntegerField(db_column='InUse')),
                ('pastinglength', models.FloatField(db_column='PastingLength')),
                ('avgspeed', models.FloatField(db_column='AvgSpeed')),
                ('makeready', models.FloatField(db_column='MakeReady')),
                ('narration2', models.CharField(db_column='Narration2', max_length=200)),
                ('pastingadhesiveid', models.CharField(db_column='PastingAdhesiveID', max_length=10)),
                ('pastingmakereadytime', models.FloatField(db_column='PastingMakeReadyTime')),
                ('speedpersqmeter', models.FloatField(db_column='SpeedPerSqMeter')),
                ('fromlengthcm', models.FloatField(db_column='FromLengthcm')),
                ('tolengthcm', models.FloatField(db_column='ToLengthcm')),
                ('iscorrugated', models.IntegerField(db_column='IsCorrugated')),
                ('cartonstyles', models.CharField(db_column='CartonStyles', max_length=500)),
                ('adhesivegsm', models.FloatField(db_column='AdhesiveGSM')),
            ],
            options={
                'db_table': 'pastingmaster',
                'managed': False,
            },
        ),
    ]
